# Generated by Django 5.2.9 on 2026-01-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0003_alter_borrowing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["-id"]},
        ),
    ]
